SERVICES = {
    :server => {
        :name => 'mkulikovS',
        :ip => '192.168.56.110',
        
    }
}

PROVIDER = {
    'vb' => {
        :memory => 1024,
        :cpus => 1,
    }
}

Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-13"
    config.vm.provision "shell", name: "set_up_server", path: "scripts/server.sh"

    config.vm.define SERVICES[:server][:name] do |config|
        config.vm.hostname = SERVICES[:server][:name]
        config.vm.network "private_network", ip: SERVICES[:server][:ip]
        config.vm.post_up_message = "#{SERVICES[:server][:name]} is up and running at #{SERVICES[:server][:ip]}"
        config.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--name", SERVICES[:server][:name]]
            vb.memory = PROVIDER['vb'][:memory]
            vb.cpus = PROVIDER['vb'][:cpus]
        end
    end
end
