SERVICES = {
    :server => {
        :name => 'mkulikovS',
        :ip => '192.168.56.110',
        
    },
    :server_worker => {
        :name => 'mkulikovSW',
        :ip => '192.168.56.111',
        
    },
}

PROVIDER = {
    'vb' => {
        :memory => 512,
        :cpus => 1,
    }
}

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.define SERVICES[:server][:name] do |config|
            config.vm.hostname = SERVICES[:server][:name]
            config.vm.network "private_network", ip: SERVICES[:server][:ip]
            config.vm.post_up_message = "#{SERVICES[:server][:name]} is up and running at #{SERVICES[:server][:ip]}"
            config.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--name", SERVICES[:server][:name]]
                vb.memory = PROVIDER['vb'][:memory]
                vb.cpus = PROVIDER['vb'][:cpus]
            end
            # config.vm.provision :shell, :inline => SHELL
        # SHELL
            # control.vm.provision "shell", path: REDACTED
    end

    config.vm.define SERVICES[:server_worker][:name] do |config|
            config.vm.hostname = SERVICES[:server_worker][:name]
            config.vm.network "private_network", ip: SERVICES[:server_worker][:ip]
            config.vm.post_up_message = "#{SERVICES[:server_worker][:name]} is up and running at #{SERVICES[:server_worker][:ip]}"
            config.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--name", SERVICES[:server_worker][:name]]
                vb.memory = PROVIDER['vb'][:memory]
                vb.cpus = PROVIDER['vb'][:cpus]
            end
            
            # config.vm.provision :shell, :inline => SHELL
        # SHELL
            # control.vm.provision "shell", path: REDACTED
    end
end
